services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
      - ~/.ssh:/home/vscode/.ssh:cached
    ports:
      - '3000:3000'
    command: sleep infinity
